namespace Alore.Player.Packets.Outgoing
{
    using Alore.API.Network.Packets;

    public class CfhTopicsInitComposer : ServerPacket
    {
        public CfhTopicsInitComposer()
            : base(Headers.CfhTopicsInitMessageComposer)
        {
            WriteInt(6);
            WriteString("sex_and_pii");
            WriteInt(8);
            WriteString("sexual_webcam_images");
            WriteInt(1);
            WriteString("mods");
            WriteString("sexual_webcam_images_auto");
            WriteInt(2);
            WriteString("mods");
            WriteString("explicit_sexual_talk");
            WriteInt(3);
            WriteString("mods");
            WriteString("cybersex");
            WriteInt(4);
            WriteString("mods");
            WriteString("cybersex_auto");
            WriteInt(5);
            WriteString("mods");
            WriteString("meet_some");
            WriteInt(6);
            WriteString("mods");
            WriteString("meet_irl");
            WriteInt(7);
            WriteString("mods");
            WriteString("email_or_phone");
            WriteInt(8);
            WriteString("mods");
            WriteString("scamming");
            WriteInt(3);
            WriteString("stealing");
            WriteInt(9);
            WriteString("mods");
            WriteString("scamsites");
            WriteInt(10);
            WriteString("mods");
            WriteString("selling_buying_accounts_or_furni");
            WriteInt(11);
            WriteString("mods");
            WriteString("trolling");
            WriteInt(11);
            WriteString("hate_speech");
            WriteInt(12);
            WriteString("mods");
            WriteString("violent_roleplay");
            WriteInt(13);
            WriteString("mods");
            WriteString("swearing");
            WriteInt(14);
            WriteString("auto_reply");
            WriteString("drugs");
            WriteInt(15);
            WriteString("mods");
            WriteString("gambling");
            WriteInt(16);
            WriteString("mods");
            WriteString("self_threatening");
            WriteInt(17);
            WriteString("mods");
            WriteString("mild_staff_impersonation");
            WriteInt(18);
            WriteString("mods");
            WriteString("severe_staff_impersonation");
            WriteInt(19);
            WriteString("mods");
            WriteString("habbo_name");
            WriteInt(20);
            WriteString("mods");
            WriteString("minors_access");
            WriteInt(21);
            WriteString("mods");
            WriteString("bullying");
            WriteInt(22);
            WriteString("guardians");
            WriteString("interruption");
            WriteInt(2);
            WriteString("flooding");
            WriteInt(23);
            WriteString("mods");
            WriteString("doors");
            WriteInt(24);
            WriteString("mods");
            WriteString("room");
            WriteInt(1);
            WriteString("room_report");
            WriteInt(25);
            WriteString("mods");
            WriteString("help");
            WriteInt(2);
            WriteString("help_habbo");
            WriteInt(26);
            WriteString("auto_reply");
            WriteString("help_payments");
            WriteInt(27);
            WriteString("auto_reply");
        }
    }
}
